version: '3.1'

services:
  depspacito-0:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=0"
    ports: 
      - "11000:11000"
    networks:
      rockfs:
        ipv4_address: 10.5.0.2
  depspacito-1:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=1"
    ports: 
      - "11010:11010"
    networks: 
      rockfs:
        ipv4_address: 10.5.0.3
  depspacito-2:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=2"
    ports: 
      - "11020:11020"
    networks: 
      rockfs:
        ipv4_address: 10.5.0.4
  depspacito-3:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=3"
    ports: 
      - "11030:11030"
    networks: 
      rockfs:
        ipv4_address: 10.5.0.5

networks:
  rockfs:
    driver: overlay
    ipam:
        driver: default
        config:
            - subnet: 10.5.0.0/16