#docker network create --driver overlay --attachable --subnet 10.0.6.0/24 --gateway 10.0.6.1 depspace
#docker-compose up

version: '3.1'

services:
  depspacito-0:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=0"
    ports: 
      - "11000:11000"
    networks:
      depspace:
        ipv4_address: 10.0.6.2
  depspacito-1:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=1"
    ports: 
      - "11010:11010"
    networks: 
      depspace:
        ipv4_address: 10.0.6.3
  depspacito-2:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=2"
    ports: 
      - "11020:11020"
    networks: 
      depspace:
        ipv4_address: 10.0.6.4
  depspacito-3:
    build: .
    command: bash -c "mvn clean && mvn install && mvn exec:java -P replica -Dreplica.id=3"
    ports: 
      - "11040:11040"
    networks: 
      depspace:
        ipv4_address: 10.0.6.6
        
networks:
  depspace:
    driver: overlay
    ipam:
        driver: default
        config:
        -
          subnet: 10.0.6.0/24

